name: serverless CI/CD

on:
  push:
    branches: [master]

env:
  REGION: cn-hongkong
  TIMEOUT: 300

jobs:
  serverless-cicd-job:
    name: Serverless cicd
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initializing Serverless-Devs
      uses: Serverless-Devs/serverless-devs-initialization-action@main
      with:
        provider: alibaba
        AccessKeyID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        AccessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        AccountID: ${{ secrets.ALIYUN_ACCOUNT_ID }}

    - name: Deploying
      run: sudo --preserve-env s deploy